//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6_Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public int StudentFK { get; set; }
        public int UnitFK { get; set; }
        public System.DateTime DatePlaced { get; set; }
        public int StatusFK { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Student Student { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
